#!/usr/bin/env python3
"""
scripts/figures/boundary_limited_error.py

N2 -- the keystone of the label-ceiling narrative: at the pretrained baseline the
residual segmentation error is dominated by BOUNDARY-localised label ambiguity,
not interior (capacity) failure. Three panels, one cell (baseline):

  (a) Trimap IoU recovery.  Per-class IoU re-scored while excluding a widening band
      around GROUND-TRUTH class boundaries. IoU climbs steeply then plateaus -> the
      error lives in the boundary shell. Per-seed mean over 10 seeds (+/-1 SD band),
      NOT the ensemble argmax. Trimap / boundary-band recovery (Kohli et al. 2009; Csurka et al. 2013),
      read in the exclude-the-band direction.

  (b) Error vs distance-to-boundary.  Foreground misclassification rate vs distance to
      the nearest GT boundary (log m). Decays to an interior floor -- error is
      concentrated at boundaries. Non-circular (stratified by GT boundaries, never by
      predictions). The matching entropy-vs-distance decay now lives in the uncertainty
      figure (Fig 13b), decomposed into aleatoric and epistemic parts.

  (c) Boundary-band vs interior error, per class.  Paired bars: foreground error rate in
      the boundary band (<=1.5 m of a GT boundary) vs the interior floor (>8 m). Forest and
      Settlement collapse to ~0 in the interior (purely boundary-limited -> label ceiling);
      Seminatural keeps a non-zero interior floor (genuine interior/semantic error), which we
      own. Discriminates failure modes per class, unlike a Mask/Boundary-IoU gap (which just
      tracks Mask-IoU level). Cheng et al. (2021) Boundary-IoU + d-sweep are still computed in
      the JSON (boundary_iou block) for a supplementary table.

Data (all three panels from ONE file, all on the same 219 Irish val tiles):
  analysis/label_ceiling/boundary_trimap_<cell>.json
    recovery_trimap   -> (a)   boundary_iou -> (c)
    error_vs_distance -> (b)   error_rate_foreground + entropy_total_foreground
  regenerated by: PYTHONPATH=. python scripts/analysis/boundary_trimap_iou.py

Output:
  figures/boundary_limited_error.pdf  (+ .png for QC)

  New-narrative figure; intentionally NOT in build_all_figures.py.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

# Palette shared with frequency_vs_difficulty.py / class_distributions.py.
# Keys are STUDENT_CLASSES names (geoseg.taxonomy), matching the analysis JSON.
RGB = {
    "Forest": (250, 62, 119),
    "Grassland": (168, 232, 84),
    "Cropland": (242, 180, 92),
    "Settlement": (59, 141, 247),
    "Seminatural": (255, 214, 33),
}
SHORT = {
    "Forest": "Forest",
    "Grassland": "Grassland",
    "Cropland": "Cropland",
    "Settlement": "Settlement",
    "Seminatural": "Semi-nat.",
}
# Class order for the panel-(c) bars (canonical foreground order).
BAR_ORDER = ["Forest", "Grassland", "Cropland", "Settlement", "Seminatural"]
# Narrative classes traced in panel (a).
TRACE = ["Forest", "Settlement", "Seminatural"]
GSD_M = 0.5  # NOTE: inland only; see GSD_BY_SITE
# Per-site ground sample distance: ONE definition, in geoseg/geo.py. This exact block was
# duplicated verbatim in four files, and gsd_for() silently returned the inland (0.5, 0.5) for any
# site it did not recognise -- rescaling every boundary distance by up to 28% in x without a word.
# It now raises. geoseg/geo.py also records why the registered values are the spherical
# approximation rather than the 0.2%-larger geodesic one.
# (no geoseg.geo import: nothing here uses it. It was added by the 2026-07-26 constant
# de-literalisation and left behind unused. build_all_figures.py runs figure scripts as
# `subprocess.run([sys.executable, script], cwd=REPO_ROOT)`, and cwd is NOT on sys.path in
# Python 3.11, so a dead top-level `from geoseg...` is a hard ModuleNotFoundError under the
# shipped invocation even though it imports fine with PYTHONPATH=. set.)



def find_repo_root() -> Path:
    p = Path.cwd().resolve()
    for _ in range(10):
        if (p / "data").is_dir() and (p / "scripts").is_dir():
            return p
        if p == p.parent:
            break
        p = p.parent
    p = Path(__file__).resolve()
    for parent in p.parents:
        if (parent / "artifacts").is_dir() and (parent / "scripts").is_dir():  # not data/: gitignored
            return parent
    raise RuntimeError("Could not find repo root")


def setup_font(use_tex: bool):
    rc = {
        "font.family": "serif",
        "font.serif": ["Computer Modern Roman"],
        "axes.labelsize": 14,
        "font.size": 13,
        "axes.titlesize": 14,
        "legend.fontsize": 13,
        "xtick.labelsize": 12.5,
        "ytick.labelsize": 12.5,
        "axes.axisbelow": True,
        "figure.dpi": 150,
    }
    if use_tex:
        rc["text.usetex"] = True
        rc["text.latex.preamble"] = r"\usepackage{amsmath}"
    else:
        rc["text.usetex"] = False
        rc["mathtext.fontset"] = "cm"
    plt.rcParams.update(rc)


def col(name):
    return np.array(RGB[name]) / 255.0


def panel_distance(ax, err, use_tex):
    """(b) foreground error rate vs distance-to-boundary (single axis).
    Entropy-vs-distance now lives in the uncertainty figure (Fig 13b)."""
    em = err["edges_m"]
    # bin centres; final open bin (inf) plotted at 1.4x the last finite edge.
    fin = [e for e in em if np.isfinite(e)]
    cen = [(a + b) / 2 for a, b in zip(fin[:-1], fin[1:])] + [fin[-1] * 1.4]
    rate = np.array(err["error_rate_foreground"])
    ax.plot(cen, rate, "-o", ms=3.5, lw=1.5, color="#b2182b", zorder=3)
    ax.set_xscale("log")
    ax.set_xlabel("distance to GT boundary (m, log)")
    ax.set_ylabel("misclassification rate")
    ax.set_title("(a)")
    ax.grid(True, ls=":", lw=0.5, color="#cccccc")


def panel_interior_floor(ax, bvi, use_tex):
    """(c) per-class error rate in the CONTACT ZONE vs the interior floor.

    The near band here is 1.5 m, not the registered 8 m boundary band -- this panel does not
    show rho. Boundary-limited (label-ceiling) classes collapse to ~0 in the interior; a class
    with a non-zero interior floor (Seminatural) has genuine interior/semantic error."""
    pc = bvi["per_class"]
    bmax, imin = bvi["contact_max_m"], bvi["interior_min_m"]
    names = BAR_ORDER
    x = np.arange(len(names))
    w = 0.38
    bnd = [pc[n]["boundary_error"] for n in names]
    inr = [pc[n]["interior_error"] for n in names]
    cols = [col(n) for n in names]
    ax.bar(x - w / 2, bnd, w, color=cols, edgecolor="black", lw=0.6)
    ax.bar(x + w / 2, inr, w, color=cols, edgecolor="black", lw=0.6, alpha=0.4, hatch="///")
    ax.set_xticks(x)
    ax.set_xticklabels([SHORT[n] for n in names], rotation=30, ha="right")
    ax.set_ylabel("misclassification rate")
    ax.set_ylim(0, max(bnd) * 1.18)
    ax.set_title("(b)")
    ax.grid(True, axis="y", ls=":", lw=0.5, color="#cccccc")
    from matplotlib.patches import Patch
    blab = (rf"contact zone ($\leq{bmax:g}$\,m)" if use_tex else f"contact zone (<={bmax:g} m)")
    ilab = (rf"interior ($>{imin:g}$\,m)" if use_tex else f"interior (>{imin:g} m)")
    handles = [Patch(facecolor="#999999", edgecolor="black", label=blab),
               Patch(facecolor="#999999", edgecolor="black", alpha=0.4, hatch="///", label=ilab)]
    ax.legend(handles=handles, loc="upper center", frameon=False)


def trimap_json(root, split, cell):
    """The trimap JSON for one cell on one held-out split, as RUNBOOK stage D writes it.

    Stage D runs `boundary_trimap_iou.py --out-dir analysis/label_ceiling/$SPLIT` for SPLIT in
    {test, external_test}, so the file is PER SPLIT. This script read the un-split path
    `analysis/label_ceiling/boundary_trimap_<cell>.json` until 2026-07-27, which stage D never
    writes -- so the paper's boundary figure could not be built from the campaign's own output.
    Nothing wrote that path except a bare `boundary_trimap_iou.py` run taking its own default
    --out-dir, which is Test A only and records no split, so the failure mode on a debug run was
    not a crash but a manuscript figure of unrecorded provenance.
    """
    p = root / f"analysis/label_ceiling/{split}/boundary_trimap_{cell}.json"
    if not p.exists():
        legacy = root / f"analysis/label_ceiling/boundary_trimap_{cell}.json"
        extra = (f"\n  NOTE: {legacy.relative_to(root)} exists. That is the un-split legacy path, "
                 f"written only by a bare boundary_trimap_iou.py run; it records no split and is "
                 f"NOT stage D output. Refusing it rather than plotting unrecorded provenance."
                 if legacy.exists() else "")
        raise SystemExit(
            f"{p.relative_to(root)} not found.\n"
            f"  Produce it with RUNBOOK stage D, which writes one file per held-out split:\n"
            f"    bash RUNBOOK.sh --from D --to D\n"
            f"  or pass --split {{test,external_test}} to name the one you mean.{extra}")
    return p


def render(root, out_dir, cell, use_tex, split="test"):
    setup_font(use_tex)
    bt = json.load(open(trimap_json(root, split, cell)))

    # PANEL (a), TRIMAP IoU RECOVERY, WAS DROPPED 2026-07-29. It is the withdrawn claim itself:
    # IoU climbing as a widening boundary band is excluded IS "the residual error is
    # boundary-limited", which this paper does not claim and `docs/DO_NOT_ADD.md` forbids. Panels
    # (b) and (c) survive because they carry two sentences the paper does make -- that this map
    # follows the usual boundary pattern (so the grassland pair is an exception to it, not evidence
    # of unusually clean edges), and that the two classes differ in how deep their error runs.
    # `panel_recovery` was deleted with it -- the recovery_trimap JSON block is still written,
    # so a supplementary table can be built from the data without keeping a drawing of a
    # withdrawn claim in the tree.
    #
    # Width is 7.28 in, for \begin{adjustwidth}{-\extralength}{0cm} -- \textwidth is 13.90 cm and
    # \extralength 4.61 cm, so a figure built wider is scaled down and every label with it.
    fig, axes = plt.subplots(1, 2, figsize=(7.28, 3.9))
    panel_distance(axes[0], bt["error_vs_distance"], use_tex)
    panel_interior_floor(axes[1], bt["error_vs_distance"]["contact_zone_vs_interior"], use_tex)

    # Shared class legend at the bottom (panel c uses the class colours).
    from matplotlib.lines import Line2D
    handles = [Line2D([0], [0], color=col(n), lw=2.4, label=SHORT[n]) for n in BAR_ORDER]
    handles.append(Line2D([0], [0], color="#444444", lw=1.6, ls="--", label="macro (fg)"))
    fig.legend(handles=handles, loc="lower center", ncol=6, frameon=False,
               bbox_to_anchor=(0.5, -0.01), columnspacing=1.4, handletextpad=0.5)
    fig.tight_layout(rect=[0, 0.07, 1, 1])

    out_dir.mkdir(parents=True, exist_ok=True)
    pdf = out_dir / "boundary_limited_error.pdf"
    png = out_dir / "boundary_limited_error.png"
    fig.savefig(pdf, bbox_inches="tight")
    fig.savefig(png, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"[boundary_limited_error] cell={cell} -> {pdf}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cell", default="stage3_clsbal")
    ap.add_argument("--split", default="test", choices=["test", "external_test"],
                    help="which held-out split's trimap curve to plot. Test A (test) is the "
                         "default; Test B (external_test) is the upland transfer set. Never "
                         "validation -- every checkpoint is selected on it.")
    ap.add_argument("--out-dir", default="figures")
    ap.add_argument("--no-tex", action="store_true")
    args = ap.parse_args()
    root = find_repo_root()
    out_dir = (root / args.out_dir).resolve()
    use_tex = not args.no_tex
    try:
        render(root, out_dir, args.cell, use_tex, args.split)
    except SystemExit:
        # A missing/refused input is not a font problem. Retrying it under mathtext would report
        # "usetex failed" for a file that does not exist, hiding the real cause behind a wrong one.
        raise
    except Exception as e:
        if not use_tex:
            raise
        print(f"[boundary_limited_error] usetex failed ({e}); retrying with mathtext")
        render(root, out_dir, args.cell, use_tex=False, split=args.split)


if __name__ == "__main__":
    main()
