#!/usr/bin/env python3
"""
scripts/figures/build_all_figures.py

Single entry point to reproduce the manuscript figures that render directly to figures/.

Usage:
  python scripts/figures/build_all_figures.py [--device cuda|cpu] [--skip <name> ...]

Figures use stable DESCRIPTIVE names (the printed numbers are assigned by LaTeX).
  - workflow_pipeline, mitigation_axes, oem_mapping are TikZ (.tex), compiled with
    pdflatex and copied to figures/.
  - study_area, class_distributions, ablation_qualitative, confusion_matrices,
    frequency_vs_difficulty, reliability_ece, uncertainty_quality,
    boundary_limited_error are Python scripts that write directly to figures/.
  - All figures read saved outputs/artifacts (no GPU required).

The uncertainty-overlay, class-pair-boundary, and confident-learning cross-check figures are
produced by scripts/analysis/* (they depend on saved per-tile evaluation outputs) and copied
in under their final names.
Freshly built figures are synced into the submission bundle (manuscript/Figures/), which is
where the manuscript reads them. Pass --skip <name> to skip by the descriptive key. The
graphical abstract is built separately (graphical_abstract_panels.py + graphical_abstract_tikz.tex).
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


SCRIPTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPTS_DIR.parent.parent
FIGURES_DIR = REPO_ROOT / "figures"
ANALYSIS_SCRIPTS_DIR = REPO_ROOT / "scripts" / "analysis"
LABEL_CEILING_DIR = REPO_ROOT / "analysis" / "label_ceiling"
SUBMISSION_FIGS_DIR = REPO_ROOT / "manuscript" / "Figures"


def run_py(script: Path, extra_args: list[str], device: str) -> bool:
    if not script.exists():
        print(f"\nERROR: script not found: {script}")
        return False
    cmd = [sys.executable, str(script), f"--device={device}", *extra_args]
    print(f"\n{'='*60}\nRunning: {script.name}\n{'='*60}")
    return subprocess.run(cmd, cwd=str(REPO_ROOT)).returncode == 0


def run_py_no_device(script: Path) -> bool:
    """For scripts that do not accept a --device argument."""
    if not script.exists():
        print(f"\nERROR: script not found: {script}")
        return False
    cmd = [sys.executable, str(script)]
    print(f"\n{'='*60}\nRunning: {script.name}\n{'='*60}")
    return subprocess.run(cmd, cwd=str(REPO_ROOT)).returncode == 0


def run_tex(tex: Path) -> bool:
    """Compile a standalone TikZ figure and copy the PDF into figures/."""
    if not tex.exists():
        print(f"\nERROR: source not found: {tex}")
        return False
    print(f"\n{'='*60}\nCompiling: {tex.name}\n{'='*60}")
    cmd = ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex.name]
    ok = subprocess.run(cmd, cwd=str(SCRIPTS_DIR)).returncode == 0
    produced = SCRIPTS_DIR / (tex.stem + ".pdf")
    if not ok or not produced.exists():
        return False
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(produced, FIGURES_DIR / produced.name)
    # tidy LaTeX side products
    for ext in (".aux", ".log"):
        (SCRIPTS_DIR / (tex.stem + ext)).unlink(missing_ok=True)
    return True


def run_analysis(script_name: str, produced: str, final_name: str) -> bool:
    """Run a scripts/analysis figure script and copy its output into figures/ under the
    final manuscript name (these figures depend on saved per-tile evaluation outputs)."""
    script = ANALYSIS_SCRIPTS_DIR / script_name
    if not script.exists():
        print(f"\nERROR: script not found: {script}")
        return False
    print(f"\n{'='*60}\nRunning: {script_name}\n{'='*60}")
    ok = subprocess.run([sys.executable, str(script)], cwd=str(REPO_ROOT)).returncode == 0
    src = LABEL_CEILING_DIR / produced
    if not ok or not src.exists():
        return False
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, FIGURES_DIR / final_name)
    return True


def main() -> None:
    ap = argparse.ArgumentParser(description="Build all manuscript figures.")
    ap.add_argument("--device", default="cuda", choices=["cuda", "cpu"],
                    help="Device for scripts that run model inference (default: cuda).")
    ap.add_argument("--skip", nargs="*", default=[],
                    help="Descriptive figure keys to skip, e.g. --skip study_area confusion_matrices")
    args = ap.parse_args()

    skip = set(args.skip)

    # Manuscript figures that write directly to figures/ (descriptive names; LaTeX
    # assigns the printed numbers). oem_mapping's numeric content is generated by
    # _gen_mapping_values.py from the frozen teacher confusion.
    figures: list[tuple[str, callable]] = [
        ("workflow_pipeline",      lambda: run_tex(SCRIPTS_DIR / "workflow_pipeline.tex")),
        ("oem_mapping",            lambda: run_tex(SCRIPTS_DIR / "oem_mapping.tex")),
        ("study_area",             lambda: run_py_no_device(SCRIPTS_DIR / "study_area.py")),
        ("class_distributions",    lambda: run_py_no_device(SCRIPTS_DIR / "class_distributions.py")),
        ("ablation_qualitative",   lambda: run_py_no_device(SCRIPTS_DIR / "ablation_qualitative.py")),
        ("confusion_matrices",     lambda: run_py_no_device(SCRIPTS_DIR / "confusion_matrices.py")),
        ("boundary_limited_error", lambda: run_py_no_device(SCRIPTS_DIR / "boundary_limited_error.py")),
    ]
    # CUT 2026-07-28, six figures. Five no longer support a surviving conclusion and one is refuted
    # by the study's own data. They were not merely unused: four read inputs that moved to
    # `_archive/withdrawn_campaign_2026-07-28/` when the withdrawn campaign was cleared away, so this
    # list raised SystemExit and refused to sync even the seven figures that had built.
    #   mitigation_axes           schematic of a data-vs-model split the fixed architecture cannot test
    #   frequency_vs_difficulty   five classes cannot support the claim in either direction
    #   reliability_ece           residual-uncertainty section, cut
    #   uncertainty_quality       same
    #   uncertainty_overlay       same
    #   confident_learning_overlay  appendix cut; its headline was a retracted statistic
    # Their scripts remain under scripts/ and scripts/analysis/ and can still be run by hand.

    results: dict[str, bool | str] = {}
    for fig_num, runner in figures:
        if fig_num in skip:
            results[fig_num] = "skipped"
            print(f"\nSkipping Figure {fig_num} (--skip).")
            continue
        results[fig_num] = runner()

    print(f"\n{'='*60}\nBuild summary\n{'='*60}")
    for fig_num, status in results.items():
        marker = "SKIP" if status == "skipped" else ("OK  " if status is True else "FAIL")
        print(f"  Figure {fig_num}: {marker}")

    failed = [n for n, s in results.items() if s is False]

    # Sync into the submission bundle (main.tex reads from manuscript/Figures/) ONLY when every
    # requested figure built. Copying the ones that happened to succeed leaves the manuscript with a
    # mixture of fresh and stale figures and no way to tell which is which -- and the stale ones are
    # from the withdrawn leaking campaign.
    if failed:
        print(f"\n{len(failed)} figure(s) failed: {', '.join(failed)}")
        print(f"NOT syncing to {SUBMISSION_FIGS_DIR.relative_to(REPO_ROOT)}/ — a partial sync mixes "
              f"fresh figures with whatever was there before, undetectably.")
        sys.exit(1)
    if SUBMISSION_FIGS_DIR.is_dir():
        for name, status in results.items():
            pdf = FIGURES_DIR / f"{name}.pdf"
            if status is True and pdf.exists():
                shutil.copyfile(pdf, SUBMISSION_FIGS_DIR / f"{name}.pdf")
        print(f"\nSynced built figures -> {SUBMISSION_FIGS_DIR.relative_to(REPO_ROOT)}/")
    print("\nAll requested figures built successfully.")


if __name__ == "__main__":
    main()
